services:
  degubase:
    build: .
    ports:
      - "8080:8080"
    environment:
      DEGUBASE_HOST: "0.0.0.0"
      DEGUBASE_DATA_DIR: /data
      DEGUBASE_CONFIG_DIR: /config
    volumes:
      - data:/data
      - config:/config
    restart: unless-stopped

volumes:
  data:
  config:
