// Hex values drawn from palette 0 (Set 1) and palette 1 (Set 2) in palettes.js
// so select chip colours feel native alongside user-created columns.
const C = {
  red:    '#e41a1c',
  blue:   '#377eb8',
  green:  '#4daf4a',
  purple: '#984ea3',
  orange: '#ff7f00',
  brown:  '#a65628',
  pink:   '#f781bf',
  teal:   '#66c2a5',
  yellow: '#e6ab02',
  gray:   '#b3b3b3',
}

function sel(choices) {
  return {
    choices: choices.map(c => c[0]),
    choiceColors: Object.fromEntries(choices.map(c => [c[0], c[1]])),
    palette: 0,
  }
}

function col(name, type, options) {
  return options ? { name, type, options } : { name, type }
}

// Shared option sets reused across templates
const STATUS_TASK = sel([
  ['Backlog',     C.gray  ],
  ['In Progress', C.blue  ],
  ['In Review',   C.orange],
  ['Done',        C.green ],
  ['Blocked',     C.red   ],
])

const PRIORITY = sel([
  ['Low',      C.teal  ],
  ['Medium',   C.yellow],
  ['High',     C.orange],
  ['Critical', C.red   ],
])

export const TEMPLATE_GROUPS = [
  {
    label: 'Standard',
    templates: [
      {
        id: 'crm',
        name: 'CRM',
        description: 'Track contacts, companies, and deal stages.',
        icon: '👥',
        columns: [
          col('Name', 'text'),
          col('Company', 'text'),
          col('Email', 'email'),
          col('Phone', 'text'),
          col('Stage', 'single-select', sel([
            ['Lead',        C.gray  ],
            ['Qualified',   C.blue  ],
            ['Proposal',    C.orange],
            ['Negotiation', C.yellow],
            ['Closed Won',  C.green ],
            ['Closed Lost', C.red   ],
          ])),
          col('Last Contact', 'date'),
          col('Notes', 'long-text'),
        ],
      },
      {
        id: 'task-tracker',
        name: 'Task Tracker',
        description: 'Lightweight task board without the overhead.',
        icon: '✅',
        columns: [
          col('Task', 'text'),
          col('Owner', 'text'),
          col('Status', 'single-select', STATUS_TASK),
          col('Priority', 'single-select', PRIORITY),
          col('Due Date', 'date'),
          col('Notes', 'long-text'),
        ],
      },
      {
        id: 'initiatives',
        name: 'Initiatives',
        description: 'Capture strategic initiatives: what, why, who, and when.',
        icon: '🚀',
        columns: [
          col('Name', 'text'),
          col('Status', 'single-select', sel([
            ['Idea',     C.gray  ],
            ['Proposed', C.blue  ],
            ['Approved', C.teal  ],
            ['Active',   C.orange],
            ['Done',     C.green ],
            ['Dropped',  C.red   ],
          ])),
          col('Impact', 'single-select', sel([
            ['High',   C.green ],
            ['Medium', C.yellow],
            ['Low',    C.gray  ],
          ])),
          col('Effort', 'single-select', sel([
            ['S',  C.teal  ],
            ['M',  C.blue  ],
            ['L',  C.orange],
            ['XL', C.red   ],
          ])),
          col('Owner', 'text'),
          col('Area', 'single-select', sel([
            ['Product',       C.blue  ],
            ['Engineering',   C.teal  ],
            ['Data',          C.purple],
            ['Design',        C.pink  ],
            ['Operations',    C.orange],
          ])),
          col('Strategic Goals', 'multi-select', sel([
            ['Growth',              C.green ],
            ['Retention',           C.teal  ],
            ['Cost Reduction',      C.blue  ],
            ['Quality',             C.purple],
            ['Innovation',          C.orange],
            ['Compliance',          C.brown ],
            ['Customer Experience', C.pink  ],
          ])),
          col('Start Date', 'date'),
          col('Target Date', 'date'),
          col('Tags', 'multi-select', sel([
            ['Quick Win', C.green ],
            ['Bet',       C.orange],
            ['Platform',  C.blue  ],
            ['Debt',      C.gray  ],
          ])),
          col('Goal', 'markdown'),
        ],
      },
      {
        id: 'bug-tracker',
        name: 'Bug Tracker',
        description: 'Capture, triage, and resolve software defects.',
        icon: '🐛',
        columns: [
          col('Title', 'text'),
          col('Severity', 'single-select', PRIORITY),
          col('Status', 'single-select', sel([
            ['Open',        C.red   ],
            ['In Progress', C.orange],
            ['Fixed',       C.green ],
            ["Won't Fix",   C.gray  ],
            ['Duplicate',   C.purple],
          ])),
          col('Assignee', 'text'),
          col('Reported', 'date'),
          col('Steps to Reproduce', 'long-text'),
          col('Notes', 'long-text'),
        ],
      },
      {
        id: 'content-calendar',
        name: 'Content Calendar',
        description: 'Plan posts, newsletters, and publishing schedules.',
        icon: '📅',
        columns: [
          col('Title', 'text'),
          col('Channel', 'single-select', sel([
            ['Blog',       C.blue  ],
            ['Newsletter', C.orange],
            ['LinkedIn',   C.teal  ],
            ['X',          C.gray  ],
            ['Instagram',  C.pink  ],
            ['YouTube',    C.red   ],
          ])),
          col('Status', 'single-select', sel([
            ['Idea',      C.gray  ],
            ['Draft',     C.blue  ],
            ['In Review', C.orange],
            ['Scheduled', C.yellow],
            ['Published', C.green ],
          ])),
          col('Author', 'text'),
          col('Publish Date', 'date'),
          col('Brief', 'long-text'),
        ],
      },
    ],
  },
  {
    label: 'Strategy',
    templates: [
      {
        id: 'okr-objectives',
        name: 'Objectives',
        description: 'Define quarterly strategic objectives — the "what" of your OKR cycle.',
        icon: '🎯',
        columns: [
          col('Objective', 'text'),
          col('Owner', 'text'),
          col('Quarter', 'single-select', sel([
            ['Q1', C.teal], ['Q2', C.blue], ['Q3', C.orange], ['Q4', C.purple],
          ])),
          col('Year', 'number'),
          col('Status', 'single-select', sel([
            ['Draft',      C.gray  ],
            ['Active',     C.blue  ],
            ['Achieved',   C.green ],
            ['Missed',     C.red   ],
            ['Cancelled',  C.brown ],
          ])),
          col('Progress', 'percent'),
          col('Key Results', 'checklist'),
          col('Description', 'long-text'),
        ],
      },
      {
        id: 'risk-register',
        name: 'Risk Register',
        description: 'Track strategic risks by likelihood and impact, with mitigation actions and owners.',
        icon: '⚠️',
        columns: [
          col('Risk', 'text'),
          col('Category', 'single-select', sel([
            ['Strategic',    C.purple],
            ['Operational',  C.blue  ],
            ['Financial',    C.orange],
            ['Compliance',   C.brown ],
            ['Technical',    C.teal  ],
            ['People',       C.pink  ],
          ])),
          col('Likelihood', 'single-select', sel([
            ['Low',      C.green ],
            ['Medium',   C.yellow],
            ['High',     C.orange],
            ['Critical', C.red   ],
          ])),
          col('Impact', 'single-select', sel([
            ['Low',      C.green ],
            ['Medium',   C.yellow],
            ['High',     C.orange],
            ['Critical', C.red   ],
          ])),
          col('Status', 'single-select', sel([
            ['Open',       C.red   ],
            ['Mitigating', C.orange],
            ['Accepted',   C.yellow],
            ['Closed',     C.green ],
          ])),
          col('Owner', 'text'),
          col('Mitigation', 'long-text'),
          col('Review Date', 'date'),
          col('Notes', 'long-text'),
        ],
      },
      {
        id: 'okr-key-results',
        name: 'Key Results',
        description: 'Track measurable outcomes that define success for each objective.',
        icon: '📈',
        columns: [
          col('Key Result', 'text'),
          col('Objective', 'text'),
          col('Owner', 'text'),
          col('Status', 'single-select', sel([
            ['Not Started', C.gray  ],
            ['On Track',    C.green ],
            ['At Risk',     C.orange],
            ['Behind',      C.red   ],
            ['Done',        C.teal  ],
          ])),
          col('Start Value',   'number'),
          col('Current Value', 'number'),
          col('Target Value',  'number'),
          col('Unit', 'text'),
          col('Due Date', 'date'),
          col('Initiatives', 'checklist'),
          col('Notes', 'long-text'),
        ],
      },
    ],
  },
  {
    label: 'Personal',
    templates: [
      {
        id: 'expense-log',
        name: 'Expense Log',
        description: 'Simple spending log for individuals or households.',
        icon: '💸',
        columns: [
          col('Date', 'date'),
          col('Description', 'text'),
          col('Category', 'single-select', sel([
            ['Housing',       C.blue  ],
            ['Food',          C.orange],
            ['Transport',     C.teal  ],
            ['Health',        C.green ],
            ['Entertainment', C.purple],
            ['Shopping',      C.pink  ],
            ['Other',         C.gray  ],
          ])),
          col('Amount', 'currency'),
          col('Account', 'single-select', sel([
            ['Cash',        C.green ],
            ['Checking',    C.blue  ],
            ['Credit Card', C.orange],
            ['Savings',     C.teal  ],
          ])),
          col('Notes', 'text'),
        ],
      },
      {
        id: 'recipe-book',
        name: 'Recipe Book',
        description: 'Store recipes with enough structure to filter and plan meals.',
        icon: '🍽️',
        columns: [
          col('Name', 'text'),
          col('Cuisine', 'single-select', sel([
            ['Italian',       C.green ],
            ['Asian',         C.red   ],
            ['Mexican',       C.orange],
            ['American',      C.blue  ],
            ['Mediterranean', C.teal  ],
            ['Other',         C.gray  ],
          ])),
          col('Prep Time (min)', 'number'),
          col('Servings', 'number'),
          col('Rating', 'rating'),
          col('Ingredients', 'long-text'),
          col('Instructions', 'long-text'),
        ],
      },
      {
        id: 'reading-list',
        name: 'Reading List',
        description: 'Track books read, currently reading, and want to read.',
        icon: '📚',
        columns: [
          col('Title', 'text'),
          col('Author', 'text'),
          col('Status', 'single-select', sel([
            ['Want to Read', C.blue  ],
            ['Reading',      C.orange],
            ['Done',         C.green ],
            ['Abandoned',    C.gray  ],
          ])),
          col('Rating', 'rating'),
          col('Started', 'date'),
          col('Finished', 'date'),
          col('Notes', 'long-text'),
        ],
      },
      {
        id: 'subscriptions',
        name: 'Subscriptions',
        description: "Know what you're paying for and when it renews.",
        icon: '💳',
        columns: [
          col('Service', 'text'),
          col('Category', 'single-select', sel([
            ['Software',  C.blue  ],
            ['Streaming', C.red   ],
            ['News',      C.orange],
            ['Health',    C.green ],
            ['Utilities', C.teal  ],
            ['Other',     C.gray  ],
          ])),
          col('Cost', 'currency'),
          col('Billing Cycle', 'single-select', sel([
            ['Monthly', C.blue  ],
            ['Annual',  C.green ],
            ['Weekly',  C.orange],
          ])),
          col('Next Renewal', 'date'),
          col('Active', 'checkbox'),
          col('Notes', 'text'),
        ],
      },
      {
        id: 'decision-journal',
        name: 'Decision Journal',
        description: 'Record why decisions were made. Revisit to close the loop.',
        icon: '🧠',
        columns: [
          col('Decision', 'text'),
          col('Context', 'long-text'),
          col('Alternatives Considered', 'long-text'),
          col('Expected Outcome', 'long-text'),
          col('Decided On', 'date'),
          col('Decided By', 'text'),
          col('Actual Outcome', 'long-text'),
          col('Status', 'single-select', sel([
            ['Pending',   C.blue ],
            ['Validated', C.green],
            ['Reversed',  C.red  ],
          ])),
        ],
      },
      {
        id: 'waiting-for',
        name: 'Waiting For',
        description: 'Track delegated items. Close open loops before they close you.',
        icon: '⏳',
        columns: [
          col('Item', 'text'),
          col('Delegated To', 'text'),
          col('Delegated On', 'date'),
          col('Expected By', 'date'),
          col('Status', 'single-select', sel([
            ['Waiting',   C.blue  ],
            ['Received',  C.green ],
            ['Overdue',   C.red   ],
            ['Cancelled', C.gray  ],
          ])),
          col('Follow-up Notes', 'long-text'),
        ],
      },
    ],
  },
  {
    label: 'Coding Agents',
    templates: [
      {
        id: 'agent-orchestration',
        name: 'Agent Orchestration',
        description: 'Coordinate multi-agent workflows with dependency tracking.',
        icon: '🤖',
        columns: [
          col('Task / Goal', 'text'),
          col('Agent Role', 'single-select', sel([
            ['Planner',    C.purple],
            ['Executor',   C.blue  ],
            ['Reviewer',   C.orange],
            ['Researcher', C.teal  ],
            ['Integrator', C.green ],
          ])),
          col('Assigned Agent', 'text'),
          col('Status', 'single-select', sel([
            ['Pending', C.gray  ],
            ['Running', C.blue  ],
            ['Blocked', C.red   ],
            ['Done',    C.green ],
            ['Failed',  C.brown ],
          ])),
          col('Depends On (task IDs)', 'text'),
          col('Input Artifacts', 'long-text'),
          col('Output Artifacts', 'long-text'),
          col('Failure Reason', 'long-text'),
          col('Started', 'date'),
          col('Completed', 'date'),
        ],
      },
      {
        id: 'evidence-trail',
        name: 'Evidence Trail',
        description: 'Agents document decisions and reasoning for audit and handoff.',
        icon: '🔍',
        columns: [
          col('Claim / Decision', 'text'),
          col('Evidence', 'long-text'),
          col('Alternatives Rejected', 'long-text'),
          col('References', 'long-text'),
          col('Confidence', 'single-select', sel([
            ['High',      C.green ],
            ['Medium',    C.yellow],
            ['Low',       C.orange],
            ['Uncertain', C.gray  ],
          ])),
          col('Agent', 'text'),
          col('Task Context', 'text'),
          col('Recorded On', 'date'),
          col('Status', 'single-select', sel([
            ['Active',      C.green ],
            ['Superseded',  C.orange],
            ['Invalidated', C.red   ],
          ])),
        ],
      },
      {
        id: 'task-memory-graph',
        name: 'Task Memory Graph',
        description: 'Dependency-aware work graph for long-horizon agent tasks.',
        icon: '🕸️',
        columns: [
          col('Title', 'text'),
          col('Type', 'single-select', sel([
            ['Goal',       C.purple],
            ['Task',       C.blue  ],
            ['Finding',    C.teal  ],
            ['Constraint', C.orange],
            ['Decision',   C.yellow],
            ['Question',   C.gray  ],
            ['Blocker',    C.red   ],
          ])),
          col('Status', 'single-select', sel([
            ['Open',        C.blue  ],
            ['In Progress', C.orange],
            ['Done',        C.green ],
            ['Blocked',     C.red   ],
            ['Deferred',    C.gray  ],
          ])),
          col('Description', 'long-text'),
          col('Depends On (row IDs)', 'text'),
          col('Blocks (row IDs)', 'text'),
          col('Context Snapshot', 'long-text'),
          col('Priority', 'single-select', PRIORITY),
          col('Agent', 'text'),
          col('Created', 'date'),
          col('Resolved', 'date'),
          col('Resolution Notes', 'long-text'),
        ],
      },
    ],
  },
]

export const ALL_TEMPLATES = TEMPLATE_GROUPS.flatMap(g => g.templates)
